baseURL = "https://arenzana.org/"
languageCode = "en-us"
title = "Isma Arenzana"
theme = "hack"
paginate = 10
copyright = "© 2024, Ismael Arenzana. All rights reserved."
description = "Someone with not a lot to say but apparently a lot to write about"
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
image = "img/featured.jpg"
googleAnalytics = ""
disqusShortname = ""

summaryLength = 20

[twitter]
    description = "Someone with not a lot to say but apparently a lot to write about"
    image = "img/IMG_3797.JPG"

[permalinks]
    blog = "/:slug/"

[params]
	subtitle = ""
	image = "img/IMG_3797.JPG"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "auto" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "CV"
url = "https://iarenzana.gitlab.io/cv/exec_en.html"
weight = 2

[[menu.main]]
name = "blog"
url = "/posts"
weight = 2

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/arenzana"

[[params.social]]
name = "X"
icon = "twitter"
url = "https://x.com/iarenzana"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
