baseURL = "https://arenzana.org/"
languageCode = "en-us"
title = "Arenzana"
theme = "hack"
paginate = 10

copyright = "© 2023, Ismael Arenzana. All rights reserved."

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""
disqusShortname = ""

summaryLength = 20

[permalinks]
    blog = "/:slug/"

[params]
	subtitle = ""
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "auto" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "CV"
url = "https://iarenzana.gitlab.io/cv/exec_en.html"
weight = 2

[[menu.main]]
name = "blog"
url = "/posts"
weight = 2

[[params.social]]
name = "Code"
icon = "code"
url = "https://github.com/arenzana"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
